# Nome do Workflow
name: CI Node.js
on:
  # Eventos que acionam o workflow, nesse caso somente na branch main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs que o workflow executará
jobs:
  # Nome do job
  build:
    # Máquina virtual onde o job será executado
    runs-on: ubuntu-latest

    # Passos (steps) que o job executará em sequência
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Fazer lint no código
        run: npm run lint
      - name: Executar testes
        run: npm test
