name: CI/CD - Node API com Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Lint
        run: npm run lint

      - name: Rodar Testes
        run: npm test

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Inicializar Terraform
        working-directory: terraform/docker
        run: terraform init

      - name: Aplicar Infraestrutura (Deploy)
        working-directory: terraform/docker
        run: terraform apply -auto-approve
